# the apiVersion is the version of spec format. this guides parsers on how to read the YAML.
# at the time of this writing the apiVersion should be backstage.io/v1alpha1 but in the future this could be
# backstage.io/v1
apiVersion: backstage.io/v1alpha1
# the `kind` denotes the type of entity. Component, API, Resource are valid values
# Component is an individual piece of software
# API is the boundaries between components
# Resource is infrastructure needed to operate a Component
kind: Component
metadata:
  # required. name of the entity
  name: Elmah
  # optional. description should be a short summarization
  description: Exception Logging Module and Handler (ELMAH)
  # optional. free-form tags
  tags:
    - csharp
    - backend
    - core-library
  # optional. hyperlinks which will appear in the catalog for the entity
  links:
    - url: https://elmah.github.io/
      title: Elmah homepage
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  # required. for Component valid values are service, website, or library
  type: library
  # required. for Component valid values are experimental, production, deprecated
  lifecycle: production
  # required. for Component this should be the name of the team owning the component
  owner: net-backend

