apiVersion: backstage.io/v1alpha1
# https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-component
kind: Component
metadata:
  # required. name of the entity
  name: Elmah
  # optional. description should be a short summarization
  description: Exception Logging Module and Handler (ELMAH)
  # optional. free-form tags
  tags:
    - csharp
    - backend
    - core-library
  # optional. hyperlinks which will appear in the catalog for the entity
  links:
    - url: https://elmah.github.io/
      title: Elmah homepage
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  # required. for Component valid values are service, website, or library
  type: library
  # required. for Component valid values are experimental, production, deprecated
  lifecycle: production
  # required. for Component this should be the name of the team owning the component
  owner: net-backend
---
apiVersion: backstage.io/v1alpha1
# https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-api
kind: API
metadata:
  # required. name of the entity
  name: Elmah-API
  # optional. description should be a short summarization
  description: An example of API docs
  # optional. free-form tags
  tags:
    - csharp
    - backend
    - rest-api
  # optional. hyperlinks which will appear in the catalog for the entity
  links:
    - url: https://elmah.github.io/
      title: Elmah homepage
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  # required. for API valid values are openapi, asyncapi, graphql, grpc
  type: openapi
  # required. for Component valid values are experimental, production, deprecated
  lifecycle: production
  # required. for Component this should be the name of the team owning the component
  owner: net-backend
  # required. based on the format defined by the spec.type
  # this can be used to load the definition of an API entity from a web server and embed it as a string in the field spec.definition
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
